language: node_js
node_js:
- 12
cache:
  directories:
  - $HOME/.npm
env:
  global:
  - IMAGE_NAME=flowcommerce/track
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
- npm run lint
branches:
  only:
  - main
